keys:
  - &users:
    - &phil_oh age12g57wqac0ertz8mqkga380d8ch0c6wq9x5nhrz0ruym6gu6x2djsajavsj
  - &hosts:
    - &lanix age1f6gza3rfg2ecgkqt5ym5m29w3lunafvzcxc2r88a5vyy4nvkrfxsht09a2
    - &m1-mbp age1m7ml8wzuc490aluwdlxp04xa2d7ffpw9qp6lru65tydyu8hw0ypq56ctn0

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *phil_oh
        - *lanix
