after-login-command = []
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'secondary'
6 = 'secondary'
7 = 'secondary'
8 = 'main'
9 = 'main'
0 = 'main'

[mode.main.binding]
alt-s= 'layout tiles horizontal vertical'
alt-a= 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 0'

alt-shift-p = ['move-workspace-to-monitor prev']
alt-shift-n = ['move-workspace-to-monitor next']

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-0 = ['move-node-to-workspace 0', 'workspace 0']

alt-shift-f = 'fullscreen'
alt-v = ['layout floating tiling', 'mode main'] 
alt-shift-minus = 'resize smart -50'
alt-shift-plus = 'resize smart +50'

[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.zotero.zotero'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'unity.Blizzard Entertainment.Hearthstone'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ScreenContinuity'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'layout floating'
